UI/WebStoreGB/Components/BrandsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebStoreGB.Domain.ViewModels;
using WebStoreGB.Interfaces.Services;

namespace WebStoreGB.Components
{
    //[ViewComponent( Name = "BrandsView")]
    public class BrandsViewComponent : ViewComponent
    {
        private readonly IProductData _ProductData;
        public BrandsViewComponent(IProductData productData)
        {
            _ProductData = productData;
        }
        //public async Task<IViewComponentResult> InvokeAsync() => View();
        public IViewComponentResult Invoke() => View(GetBrands());
        private IEnumerable<BrandViewModel> GetBrands() =>
            _ProductData.GetBrands()
            .OrderBy(x => x.Order)
            .Select(b => new BrandViewModel
            {
                Id = b.Id,
                Name = b.Name,
            });
    }
}

UI/WebStoreGB/Components/SectionsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using WebStoreGB.Domain.ViewModels;
using WebStoreGB.Interfaces.Services;

namespace WebStoreGB.Components
{
    public class SectionsViewComponent : ViewComponent 
    {
        private readonly IProductData _ProdctData;
        public SectionsViewComponent(IProductData productData) { _ProdctData = productData; }
        public IViewComponentResult Invoke()
        {
            var sections = _ProdctData.GetSections();
            var parent_sections = sections.Where(x => x.ParentId is null);

            var parent_sections_views = parent_sections
                .Select(x => new SectionViewModel
                {
                    Id = x.Id,
                    Name = x.Name,
                    Order = x.Order,
                }).ToList();

            foreach(var parent_section in parent_sections_views)
            {
                var childs = sections.Where(x => x.ParentId == parent_section.Id);
                foreach (var child_section in childs)
                    parent_section.ChildSections
                        .Add(new SectionViewModel
                        {
                            Id = child_section.Id,
                            Name = child_section.Name,
                            Order = child_section.Order,
                            Parent = parent_section
                        });
                parent_section.ChildSections.Sort((a,b) 
                    => Comparer<int>.Default.Compare(a.Order,b.Order));
            }

            parent_sections_views.Sort((a, b)
                    => Comparer<int>.Default.Compare(a.Order, b.Order));

            return View(parent_sections_views);
        }
    }
}

UI/WebStoreGB/Components/UserInfoViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebStoreGB.Components
{
    public class UserInfoViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke() => User.Identity?.IsAuthenticated == true
            ? View("UserInfo")
            : View();
    }
}

UI/WebStoreGB/Controllers/UserProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using WebStoreGB.Domain.ViewModels;
using WebStoreGB.Interfaces.Services;

namespace WebStoreGB.Controllers
{
    [Authorize]
    public class UserProfileController : Controller
    {
        public IActionResult Index() => View();

        public async Task<IActionResult> Orders([FromServices] IOrderService OrderService)
        {
            var orders = await OrderService.GetUserOrders(User.Identity!.Name);

            return View(orders.Select(o => new UserOrderViewModel
            {
                Id = o.Id,
                Address = o.Address,
                Phone = o.Phone,
                Description = o.Description,
                TotalPrice = o.TotalPrice,
                Date = o.Date,
            }));
        }
    }
}

UI/WebStoreGB/Views/Shared/Components/UserInfo/Default.cshtml
<div class="shop-menu pull-right">
    <ul class="nav navbar-nav">
        <li><a href="#"><i class="fa fa-shopping-cart"></i> Корзина</a></li>
        <li><a asp-controller="Account" asp-action="Register"><i class="fa fa-user"></i> Регистрация</a></li>
        <li><a asp-controller="Account" asp-action="Login"><i class="fa fa-lock"></i> Вход</a></li>
    </ul>
</div>

UI/WebStoreGB/Views/Shared/Components/UserInfo/UserInfo.cshtml
@using WebStoreGB.Domain.Entities.Identity

<div class="shop-menu pull-right">
    <ul class="nav navbar-nav">
        @if (User.IsInRole(Role.Administrators))
        {
            <li><a asp-area="Admin" asp-controller="Home" asp-action="Index"><i class="fa fa-keyboard-o"></i> Админка</a></li>
        }
        <li><a asp-controller="UserProfile" asp-action="index">
            <i class="fa fa-user"></i> @User.Identity!.Name</a>
        </li>
        <li><a href="#"><i class="fa fa-shopping-cart"></i> Корзина</a></li>
        <li><a asp-controller="Account" asp-action="Logout"><i class="fa fa-lock"></i> Выход</a></li>
    </ul>
</div>